- name: Install snap-store
  snap:
    name: snap-store

- name: Install flameshot
  apt:
    name:
      - flameshot
    state: present

- name: Get default favorites left bar
  become_user: "{{ user }}"
  shell:
    cmd: gsettings get org.gnome.shell favorite-apps
  register: favorites_bar

- name: Add snap-store_ubuntu-software.desktop to favorites left bar if it is not present
  become_user: "{{ user }}"
  when: "'snap-store_ubuntu-software.desktop' not in favorites_bar.stdout"
  shell: "{{ add_one_favorite_app_path }} snap-store_ubuntu-software.desktop"

- name: Add org.flameshot.Flameshot.desktop to favorites left bar if it is not present
  become_user: "{{ user }}"
  when: "'org.flameshot.Flameshot.desktop' not in favorites_bar.stdout"
  shell: "{{ add_one_favorite_app_path }} org.flameshot.Flameshot.desktop"
