- name: Install kubectl  with option --classic
  snap:
    name: kubectl
    classic: true

- name: Get architecture
  shell:
    cmd: dpkg --print-architecture
  register: architecture

- name: Download minikube
  get_url:
    url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-{{architecture.stdout}}
    dest: "{{scripts_directory}}/minikube-linux-{{architecture.stdout}}"

- name: Get architecture
  become: true
  shell:
    cmd: install {{scripts_directory}}/minikube-linux-{{architecture.stdout}} /usr/local/bin/minikube

- name: Install kubectx with option --classic
  snap:
    name: kubectx
    classic: true

- name: Install fzf (to enable interactive mode for kubectx)
  apt:
    name:
      - fzf
    state: present

- name: Install k9s
  snap:
    name: k9s
