- name: traefik
  hosts: localhost
  tasks:
    - name: Add stable chart repo traefik
      kubernetes.core.helm_repository:
        name: traefik
        repo_url: "https://traefik.github.io/charts"

    - name: Install traefik helm chart
      kubernetes.core.helm:
        name: traefik
        chart_ref: traefik/traefik
        chart_version: 24.0.0
        release_namespace: default
        create_namespace: true

    - name: Gather traefik information
      kubernetes.core.helm_info:
        name: traefik
        release_namespace: default
      register: traefik_info

    - name: Print traefik information
      debug:
        msg: "{{ traefik_info }}"
