- name: ingress-nginx
  hosts: localhost
  tasks:
    - name: Add stable chart repo ingress-nginx
      kubernetes.core.helm_repository:
        name: ingress-nginx
        repo_url: "https://kubernetes.github.io/ingress-nginx"

    - name: Install ingress-nginx helm chart
      kubernetes.core.helm:
        name: ingress-nginx
        chart_ref: ingress-nginx/ingress-nginx
        chart_version: 4.7.1
        release_namespace: ingress-nginx
        create_namespace: true

    - name: Gather ingress-nginx information
      kubernetes.core.helm_info:
        name: ingress-nginx
        release_namespace: ingress-nginx
      register: ingress_nginx_info

    - name: Print ingress-nginx information
      debug:
        msg: "{{ ingress_nginx_info }}"
