- name: Install pycharm-community with option --classic
  community.general.snap:
    name: pycharm-community
    classic: true

- name: Get default favorites left bar and add pycharm
  become_user: "{{ user }}"
  shell:
    cmd: gsettings get org.gnome.shell favorite-apps | sed "s/.$/, 'pycharm-community_pycharm-community.desktop']/"
  register: new_favorites_bar

- name: Set new favorites left bar
  become_user: "{{ user }}"
  shell:
    cmd: gsettings set org.gnome.shell favorite-apps "{{ new_favorites_bar.stdout }}"
