- name: Install pycharm-community with option --classic
  snap:
    name: pycharm-community
    classic: true

- name: Get default favorites left bar
  become_user: "{{ user }}"
  shell:
    cmd: gsettings get org.gnome.shell favorite-apps
  register: favorites_bar

- name: Add pycharm-community_pycharm-community.desktop to favorites left bar if it is not present
  become_user: "{{ user }}"
  when: "'pycharm-community_pycharm-community.desktop' not in favorites_bar.stdout"
  shell: "{{ add_one_favorite_app_path }} pycharm-community_pycharm-community.desktop"
