replicaCount: 1

service:
  type: NodePort
  port: 8080
  targetPort: 8080

networkPolicy:
  enabled: true
  ingressRules:
    customRules:
      - ports:
        - port: 8080
          protocol: TCP

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

env:
  - name: KAFKA_CLUSTERS_0_NAME
    value: "kafka"
  - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
    value: "kafka:9092"
  - name: LOGGING_LEVEL_ROOT
    value: "info"
  - name: LOGGING_LEVEL_COM_PROVECTUS
    value: "info"
