- name: Install firefox
  apt:
    name:
      - firefox
    state: present

- name: Get default favorites left bar
  become_user: "{{ user }}"
  shell:
    cmd: gsettings get org.gnome.shell favorite-apps
  register: favorites_bar

- name: Add firefox_firefox.desktop to favorites left bar if it is not present
  become_user: "{{ user }}"
  when: "'firefox_firefox.desktop' not in favorites_bar.stdout"
  shell: "{{ add_one_favorite_app_path }} google-chrome.desktop"
