- name: Make sure we have a dev group
  group:
    name: "{{ group }}"
    state: present

- name: Allow group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%{{ group }}'
    line: '%{{ group }} ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'

- name: Allow user sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^Defaults:{{ user }}'
    line: 'Defaults:{{ user }} !requiretty'
    validate: 'visudo -cf %s'

- name: Create dev user
  user:
    name: "{{ user }}"
    password: "{{ password | password_hash('sha512') }}"
    update_password: always
    group: "{{ group }}"
    state: present

- name: Create scripts directory
  file:
    path: "{{ scripts_directory }}"
    owner: "{{ user }}"
    group: "{{ group }}"
    state: directory

- name: Copy add_one_new_favorite_app.sh to scripts directory
  copy:
    src: ../../shared_files/add_one_new_favorite_app.sh
    dest: "{{ add_one_favorite_app_path }}"
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: 0744

- name: Get default favorites left bar
  become_user: "{{ user }}"
  shell:
    cmd: gsettings get org.gnome.shell favorite-apps
  register: favorites_bar

- name: Add org.gnome.Terminal.desktop to favorites left bar if it is not present
  become_user: "{{ user }}"
  when: "'org.gnome.Terminal.desktop' not in favorites_bar.stdout"
  shell: "{{ add_one_favorite_app_path }} org.gnome.Terminal.desktop"

- name: Add org.gnome.Nautilus.desktop to favorites left bar if it is not present
  become_user: "{{ user }}"
  when: "'org.gnome.Nautilus.desktop' not in favorites_bar.stdout"
  shell: "{{ add_one_favorite_app_path }} org.gnome.Nautilus.desktop"
