- name: Update the apt package index and install packages to allow apt to use a repository over HTTPS
  apt:
    update_cache: yes
    name:
      - ca-certificates
      - curl
      - gnupg
    state: present

- name: Download get-docker.sh
  get_url:
    url: https://get.docker.com
    dest: "{{scripts_directory}}/get-docker.sh"

- name: Install docker
  become_user: "{{ user }}"
  shell:
    cmd: sh {{scripts_directory}}/get-docker.sh

- name: Add user to the docker group
  become: yes
  shell:
    cmd: usermod -aG docker {{ user }}
